---
<style type="text/css">
<!--
.hang {
  text-indent: -2em;
  margin-left: 3em;
}
-->
</style>

<br> <br> 

### Journal Article

<p class = "hang">

**Zhang, Y.**, Yang, Z., & Wang, Y. (Accepted). The impact of extreme response style on the mean comparison of two independent samples. *Sage Open*
<br>  </p> <p class = "hang">

**Zhang, Y.**, Paquette, L., Baker, R. S., Bosch, N., Ocumpaugh, J., & Biswas, G. (2022). How are feelings of difficulty and familiarity linked to learning behaviors and gains in a complex science learning task? *European Journal of Psychology of Education* [https://doi.org/10.1007/s10212-022-00616-x](https://link.springer.com/article/10.1007/s10212-022-00616-x){target="_blank"} 
<br>  </p> <p class = "hang">

**Zhang, Y.**, Paquette, L., Bosch, N., Ocumpaugh, J., Biswas, G., Hutt, Stephen., \verb'&' Baker, R. S. (2022). The evolution of metacognitive strategy use in an open-ended learning environment: Do prior domain knowledge and motivation play a role? *Contemprary Educational Psychology, 69*, 102064. [https://doi.org/10.1016/j.cedpsych.2022.102064](https://www.sciencedirect.com/science/article/pii/S0361476X22000236){target="_blank"} 
<br>  </p> <p class = "hang">

**Zhang, Y.**, Paquette, L., Baker, R. S., Ocumpaugh, J., Bosch, N., Biswas, G., '& Munshi, A. (2021). Can strategic behavior facilitate confusion resolution? The interplay between confusion and metacognitive strategies in Betty's Brain. *Journal of Learning Analytics, 8*(3), 28-44. [https://doi.org/10.18608/jla.2021.7161](https://learning-analytics.info/index.php/JLA/article/view/7161){target="_blank"} 
<br>  </p> <p class = "hang">


**Zhang, Y.**, & Wang, Y. (2020). Validity of Three IRT Models for Measuring and Controlling Extreme and Midpoint Response Styles. *Frontiers in Psychology, 11*, 271. [https://doi.org/10.3389/fpsyg.2020.00271](https://www.frontiersin.org/articles/10.3389/fpsyg.2020.00271/full){target="_blank"}
<br>  </p> <p class = "hang">


Wang, Y., Ma, X., **Zhang, Y.**, Wu, L., Yang, Z., Yang, T., & Li, Y. (2019). The relationship of physical education curriculum implementation and mathematics achievement in Chinese youth. *Research Quarterly for Exercise and Sport, 90*(2), 133-140. [https://doi.org/10.3389/fpsyg.2019.01282](https://www.tandfonline.com/doi/abs/10.1080/02701367.2019.1603775){target="_blank"}
<br>  </p> <p class = "hang">

Wang, Y., Yang, Z., **Zhang, Y.**, Wang, F., Liu, T., & Xin, T. (2019). The effect of socialemotional competency on child development in western China. *Frontiers in Psychology, 10*, 1282. [https://doi.org/10.3389/fpsyg.2019.01282](https://www.frontiersin.org/articles/10.3389/fpsyg.2019.01282/full){target="_blank"}
<br>  </p> <p class = "hang">

**Zhang, Y.**, & Wang, Y. (2019). The methods for measuring and controlling response styles. *Journal of Psychological Science. 42*(3), 747-758. [https://doi.org/10.16719/j.cnki.1671-6981.20190334](https://www.psysci.org/CN/abstract/abstract10362.shtml){target="_blank"} (In Chinese) 
<br> </p><p class = "hang">

Nie, X., Chen, P., **Zhang, Y.**, & He Y. (2018). Item position effects: conceptualization, detection and developments.  *Advances in Psychological Science. 26*(2), 368-380. [https://doi.org/10.3724/SP.J.1042.2018.00368](http://journal.psych.ac.cn/xlkxjz/EN/10.3724/SP.J.1042.2018.00368){target="_blank"} (In Chinese)
<br> </p><p class = "hang">

Wang, Y., **Zhang, Y.**, & Xin T. (2018). The effect of parents’ educational aspirations on children’s mathematics achievement: Analysis of the multiple mediation effects. *Studies of Psychology and Behavior.16*(1), 96-102. [https://doi.org/xxxx1212121](http://www.xml-data.org/XYYXWYJ/html/2018/1/2018-1-96.htm){target="_blank"} (In Chinese) 
<br> </p><p class = "hang">

Wang, Y., **Zhang, Y.**, Yang, T., & Xin, T. (2017). Applications and implications of test equating in large-scale international educational assessments. *China Examinations,* (8), 43-49. [https://doi.org/10.19360/j.cnki.11-3303/g4.2017.08.008](https://www.researchgate.net/profile/Yingbin_Zhang7/publication/334507378_Applications_and_Implications_of_Test_Equating_in_Large-scale_International_Educational_Assessments/links/5d2ea06c299bf1547cbd200a/Applications-and-Implications-of-Test-Equating-in-Large-scale-International-Educational-Assessments.pdf){target="_blank"}  (In Chinese)
<br>  <br></p>


### Peer-reviewed Conference Paper
<p class = "hang">
Pinto, J. D., **Zhang, Y.**, Paquette, L., & Fan, A. X. (2021). Investigating Elements of Student Persistence in an Introductory Computer Science Course. In *Joint Proceedings of the CSEDM Workshops at the International Conference on Educational Data Mining 2021 CEUR Workshop Proceedings*. Virtual, Online. [http://ceur-ws.org/Vol-3051/CSEDM_2.pdf](http://ceur-ws.org/Vol-3051/CSEDM_2.pdf) 
<br>  </p><p class = "hang">

Bosch, N., **Zhang, Y.**, Paquette, L., Baker, R., Ocumpaugh, J., & Biswas, G. (2021). Students’ verbalized metacognition during computerized learning. In *Proceedings of the 2021 CHI Conference on Human Factors in Computing Systems (CHI '21)* (pp. 680:1-680:12). ACM, Yokohama, Japan. [https://dl.acm.org/doi/10.1145/3411764.3445809](https://doi.org/10.1145/3411764.3445809)
<br>  </p><p class = "hang">

Paquette, L., Grant, T., **Zhang, Y.**,  Biswas, G., & Baker, R. (2021). Using epistemic networks to analyze self-regulated learning in an open-ended problem-solving environment. In Ruis A.R., Lee S.B. (eds), *Advances in Quantitative Ethnography. ICQE 2021. Communications in Computer and Information Science, vol 1312* (pp. 185-201). Springer, Cham. [https://link.springer.com/chapter/10.1007/978-3-030-67788-6_13#citeas](https://doi.org/10.1007/978-3-030-67788-6_13)
<br>  </p><p class = "hang">

**Zhang, Y.**, Paquette, L., Baker, R., Ocumpaugh, J., Bosch, N., Munshi, A., & Biswas, G. (2020) The relationship between confusion and metacognitive strategies in Betty’s Brain. In *Proceedings of the 10th International Conference on Learning Analytics & Knowledge (LAK’20)* (pp. 276-284). ACM, Frankfurt, Germany. [https://doi.org/10.1145/1234567890](https://dl.acm.org/doi/10.1145/3375462.3375518)
<br>  <br></p>

### Peer-reviewed Conference Presentation
<p class = "hang">
**Zhang, Y.** & Paquette, L. (2021). Mining sequential patterns with high usage variation. Poster presented at *the 14th International Conference on Educational Data Mining (EDM '21)*. (Fully virtual conference)
<br>  </p><p class = "hang">

**Zhang, Y.** & Paquette, L. (2020). An effect-size-based temporal interestingness metric for sequential pattern mining. Poster presented at *the 13th International Conference on Educational Data Mining (EDM '20)*. (Fully virtual conference)
<br>  </p><p class = "hang">

**Zhang, Y.**, & Liu, T. (2019). Using person-fit statistics to detect response styles. Paper presented at *the National Council on Measurement in Education*, Toronto, Canada.
<br>  </p><p class = "hang">
</p>
